아아를 사먹고 잔 돈을 주는 메카니즘입니다
zzang-coding-test/conding-test pull request #13
Opened 2023-01-19 14:56 UTC by sobaman

## 문제

아아를 사먹고 잔 돈을 주는 프로그램입니다

## 푸는데 걸린 시간

## 스크린샷 (필요할 경우)

## 관련 문서 링크 (필요할 경우)

2023-01-19 19:09 UTC, ezzange requested changes

2023-01-19 19:09 UTC, ezzange commented on .gitignore
> -.project
이게 뭐야? 당신은 달라요. 다른 사람들과

2023-01-19 19:09 UTC, ezzange commented on .gitignore
> -.project
혹은 나의 실수일수도 있습니다

2023-01-19 23:28 UTC, Jeong-jeong requested changes

2023-01-19 23:28 UTC, Jeong-jeong commented on .gitignore
> -.project
@ezzange 잘 쓰셨군요 Request changes

2023-01-19 23:28 UTC, Jeong-jeong commented on soba/jan/2022-01-19-아이스 아메리카노 사먹기.java
> +            }
엄청난 while 문입니다 :)

2023-01-19 23:28 UTC, Jeong-jeong commented on .gitignore
> -.project
@sobaman  복구 필요
<img width="686" alt="image" src="https://user-images.githubusercontent.com/68528752/213584871-61fa2a1e-f3ca-40cb-8b53-e43bacb51b44.png">

2023-01-20 00:37 UTC, ezzange approved these changes

2023-01-20 00:37 UTC, ezzange commented on soba/jan/2022-01-19-아이스 아메리카노 사먹기.java
> +            }
당신은 세기의 흐름입니다.

2023-01-20 09:24 UTC, sobaman commented on soba/jan/2022-01-19-아이스 아메리카노 사먹기.java
> +            }
얼어죽어도 아아입니다

2023-01-20 12:39 UTC, Jeong-jeong approved these changes
최종 최최종 진짜최종 완전최종

2023-01-20 12:39 UTC, merged

2023-01-20 16:33 UTC, ezzange commented
축하합니다. 당신은 얻었습니다! 오늘의 할 일을