짝수 홀수 개수
zzang-coding-test/conding-test pull request #28
Opened 2023-01-23 14:16 UTC by ezzange

## 문제

문제 설명
정수가 담긴 리스트 num_list가 주어질 때, num_list의 원소 중 짝수와 홀수의 개수를 담은 배열을 return 하도록 solution 함수를 완성해보세요.

제한사항
1 ≤ num_list의 길이 ≤ 100
0 ≤ num_list의 원소 ≤ 1,000

## 푸는데 걸린 시간
10분 이내
## 깨달은 점 (필요한 경우)
배열의 왼소의 수를 지정하여 선언할 경우 아래와 같이 선언한다.
int[] answer = new int[2]; 

## 스크린샷 (필요할 경우)
![image](https://user-images.githubusercontent.com/107745857/214061303-a8833b37-313f-49b3-9efd-29ac52fc5fca.png)

## 관련 문서 링크 (필요할 경우)
[](https://school.programmers.co.kr/learn/courses/30/lessons/120824)

2023-01-23 14:42 UTC, sobaman approved these changes

2023-01-23 14:42 UTC, sobaman commented on ezz/2023-01-23-홀수 짝수 개수.java
> +    }
훌륭한 배열 활용입니다

2023-01-23 15:10 UTC, Jeong-jeong requested changes
두수의차 파일이 왜 삭제됐는가?
ezz 폴더 외부의 파일을 삭제해야 하는 듯 하다.

2023-01-24 13:58 UTC, sobaman commented on ezz/2023-01-23-홀수 짝수 개수.java
> +        int[] answer = new int[2]; //2개의 정수를 가진 answer배열 선언을 위해
비상 비상

2023-01-24 23:31 UTC, ezzange commented
우깩~~~~~~

2023-01-27 13:32 UTC, Jeong-jeong approved these changes
확이 ㄴ완료. 똥 자제 필요

2023-01-27 14:02 UTC, merged

2023-01-27 14:04 UTC, ezzange commented
@Jeong-jeong check. 오늘 많이 먹은날. 자제 노력.