나. 바보다.삼창.외치다.
zzang-coding-test/conding-test pull request #52
Opened 2023-02-01 15:04 UTC by ezzange

## 문제

문제 설명
선분 세 개로 삼각형을 만들기 위해서는 다음과 같은 조건을 만족해야 합니다.

가장 긴 변의 길이는 다른 두 변의 길이의 합보다 작아야 합니다.
삼각형의 세 변의 길이가 담긴 배열 sides이 매개변수로 주어집니다. 세 변으로 삼각형을 만들 수 있다면 1, 만들 수 없다면 2를 return하도록 solution 함수를 완성해주세요.

## 푸는데 걸린 시간
30분이상

## 깨달은 점 (필요한 경우)
사용하고 싶은게 있다면. 빌려야한다. import.

## 스크린샷 (필요할 경우)
![image](https://user-images.githubusercontent.com/107745857/216079292-39b4338e-fa5b-4173-9835-0113c2a2a29b.png)

![image](https://user-images.githubusercontent.com/107745857/216079680-5d8772ff-0893-47a1-a395-7295913f2385.png)
![image](https://user-images.githubusercontent.com/107745857/216079798-cab61c26-3329-4f63-a991-794a1f8d86a9.png)

## 관련 문서 링크 (필요할 경우)
https://school.programmers.co.kr/learn/courses/30/lessons/120889

참고블로그 
배열 오름차순 내림차순
https://coding-factory.tistory.com/549
자바 삼항연산자
https://coding-factory.tistory.com/266

2023-02-01 16:17 UTC, sobaman approved these changes
import는 사랑입니다

2023-02-02 01:01 UTC, Jeong-jeong approved these changes
import의 시작

2023-02-02 01:02 UTC, Jeong-jeong requested changes
넣으시오. feb 폴더 안에

2023-02-02 14:27 UTC, Jeong-jeong approved these changes
선승인요.

2023-02-02 14:38 UTC, merged